version: "3.3"
services:
  challenge:
    image: chainflag/eth-challenge-base:0.9.3
    ports:
      - "20000:20000"
    env_file:
      - .env
    volumes:
      - ./contracts:/home/ctf/contracts
      - ./challenge.yml:/home/ctf/challenge.yml
